# Generated by Django 3.0.4 on 2020-03-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200308_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='agreement',
            field=models.BooleanField(default=False, help_text='You need to agree to get OD'),
        ),
    ]
