# Generated by Django 3.0.4 on 2020-03-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200308_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='agreement',
            field=models.CharField(choices=[('Agreed', 'Agreed'), ('Not Agreed', 'Not Agreed')], help_text='You need to agree to get OD', max_length=10),
        ),
    ]
