# Generated by Django 3.0.4 on 2020-03-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200308_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='agreement',
            field=models.BooleanField(default=False),
        ),
    ]
