# Generated by Django 3.0.4 on 2020-03-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200308_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='agreement',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=20),
        ),
    ]
