# Generated by Django 3.0.4 on 2020-03-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200308_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='agreement',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text='You need to agree to get OD'),
        ),
    ]
