# Generated by Django 3.0.4 on 2020-03-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200308_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
